Task1
ZaycevVI/NewsApi pull request #1
Opened 2019-10-29 13:28 UTC by ZaycevVI

2019-10-30 14:27 UTC, sergey-guk-dev requested changes

2019-10-30 14:27 UTC, sergey-guk-dev commented on src/app.js
> +        _onMenuChanged.apply(this, [sources[0].id]);
мне жутко не нравится вот такой код `sources[0] ` - давай напишем свою функцию first для Array

2019-10-30 14:27 UTC, sergey-guk-dev commented on src/app.js
> +async function _onMenuChanged(id) {
а почему у тебя обработчик события находится вне класса?

2019-10-30 14:45 UTC, ZaycevVI commented on src/app.js
> +async function _onMenuChanged(id) {
это для приватности, чтобы он был недоступен извне

2019-10-31 07:55 UTC, ZaycevVI commented on src/app.js
> +        _onMenuChanged.apply(this, [sources[0].id]);
Почему-то не отображается здесь (паходу github не подхватывает изменения в лайв режиме), но изменения сделаны и в этом можно убедиться во вкладке File changed

2019-10-31 09:50 UTC, sergey-guk-dev approved these changes

2019-10-31 09:52 UTC, merged