nodejs backend for news
ZaycevVI/NewsApi pull request #3
Opened 2019-11-25 08:11 UTC by ZaycevVI

2019-11-27 16:53 UTC, sergey-guk-dev requested changes

2019-11-27 16:53 UTC, eventpromo commented on nodejs-api/controller/news-controller.js
> +            .then(data => res.send(data));
А чего здесь асинки не используешь?

2019-11-27 16:53 UTC, eventpromo commented on nodejs-api/controller/news-controller.js
> +        repository.getById(id)
Тогда бы и возвращал еще NewsModel

2019-11-27 16:53 UTC, eventpromo commented on nodejs-api/index.js
> +app.set('view engine', 'ejs');
а это тебе зачем? собираешься рендерить на серваке что-то?

2019-11-27 17:22 UTC, ZaycevVI commented on nodejs-api/controller/news-controller.js
> +        repository.getById(id)
не совсем понял о чем ты

2019-11-27 17:22 UTC, ZaycevVI commented on nodejs-api/controller/news-controller.js
> +            .then(data => res.send(data));
так они ж принципиально ничего не поменяют?

2019-12-02 13:16 UTC, sergey-guk-dev approved these changes

2019-12-02 13:18 UTC, sergey-guk-dev approved these changes

2019-12-02 13:18 UTC, merged