Task6
ZaycevVI/NewsApi pull request #5
Opened 2019-12-10 13:23 UTC by ZaycevVI

2019-12-11 13:50 UTC, sergey-guk-dev requested changes
http://webtricks-master.ru/reactjs/react-vidy-komponentov-v-react-js/

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/App.jsx
> +import FindMovieRoot from './components/find-movie/find-movie-root';
Название мне не нравится, что такое Root?

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/App.jsx
> +            <Route exact path="/" component={FindMovieRoot} />
у меня обычно деление было таким: Pages и Components. Страница обычно отвечает за управление состоянием и комбинирует компоненты, а сами компоненты как правиле стейтлесс

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/App.jsx
> +            <Route exact path="/" component={FindMovieRoot} />
Но это мой подход) Не знаю на сколько он верный)))))

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/api/film-service.js
> +        return await fetch(`${this.url}?searchBy=${search}&search=${value}&sortBy=${sort}&limit=50&sortOrder=desc`);
Не хочешь использовать билдер для конфигурации строки запроса?

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/components/find-movie/find-movie-root.jsx
> +class FindMovieRoot extends Component {
тут ты мог использоваться функциональный компонент

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/components/movie/movie-item.jsx
> +export class MovieItem extends Component {
это тоже лучше переписать на функциональный. Где у тебя просто отображение данных, то лучше использовать функциональный подход.

2019-12-11 13:50 UTC, eventpromo commented on react-app/src/components/movie/movie-root.jsx
> +    componentDidMount() {
сейчас они жутко топят за использование хуков и функциональных компонентов
https://ru.reactjs.org/docs/hooks-effect.html

2019-12-15 18:52 UTC, ZaycevVI commented on react-app/src/App.jsx
> +import FindMovieRoot from './components/find-movie/find-movie-root';
корневой компонент для каждой страницы называется по такой схеме (в моем случае их 2)

2019-12-15 18:56 UTC, ZaycevVI commented on react-app/src/App.jsx
> +            <Route exact path="/" component={FindMovieRoot} />
Не совсем понял о чем ты. Здесь используется пакет React-Dom-Router и в данном случае это один из вариантов его использования. 
Подход о котором ты говоришь (если я правильно понял), используется и у меня в приложении. Есть рутовый компонент, а есть stateless компоненты, которые использует рутовый, и передает им состояние

2019-12-15 20:39 UTC, ZaycevVI commented on react-app/src/components/movie/movie-root.jsx
> +    componentDidMount() {
от того что я поменяю вызов _componentDidMount_  на _useEffect_ хук концептуально ничего не поменяется.

2019-12-19 13:46 UTC, sergey-guk-dev approved these changes

2020-01-11 11:55 UTC, merged